---
minecraft_version: "1.17.1"

mods:
  fabric_api:
    # https://modrinth.com/mod/fabric-api
    id: { modrinth: P7dR8mSH }

  # Performance-enhancing mods:
  # https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88#fabric-117x
  # https://github.com/Madis0/fabulously-optimized/#included-mods

  # TODO: Waiting for 1.17 compatibility.
  #phosphor:
  #  # https://modrinth.com/mod/phosphor
  #  id: { modrinth: hEOCdOgW }
  #  #id: { curseforge: 372124 }
  lithium:
    # https://modrinth.com/mod/lithium
    id: { modrinth: gvQqBUqZ }
    #id: { cuseforge: 360438 }
  hydrogen:
    # https://modrinth.com/mod/hydrogen
    id: { modrinth: AZomiSrC }
  ferrite_core:
    # https://modrinth.com/mod/ferrite-core
    id: { modrinth: uXXizFIs }
    #id: { curseforge: 459857 }
  lazydfu:
    # https://modrinth.com/mod/lazydfu
    id: { modrinth: hvFnDODi }
    #id: { curseforge: 433518 }
  # TODO: Waiting for 1.17.1 compatibility.
  #smooth_boot:
  #  # https://www.curseforge.com/minecraft/mc-mods/smooth-boot
  #  # The version on Modrinth is missing the 1.17 compatibility tag.
  #  #id: { modrinth: FWumhS4T }
  #  id: { curseforge: 415758 }
  recipe_cache:
    # https://www.curseforge.com/minecraft/mc-mods/recipe-cache
    id: { curseforge: 473492 }

  servux:
    # https://www.curseforge.com/minecraft/mc-mods/servux
    id: { curseforge: 406323 }

  inventory_sorting:
    # https://www.curseforge.com/minecraft/mc-mods/inventory-sorting
    id: { curseforge: 325471 }
    # TODO: Not marked as compatible with 1.17.1.
    compatibility_override:
      filename: "InventorySorter-1.7.9-1.17.jar"
      versions: ["1.17.1"]

  xaeros_minimap_fair_play_edition:
    # https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap-fair-play-edition
    id: { curseforge: 263466 }
  xaeros_world_map:
    # https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map
    id: { curseforge: 317780 }

  # Used temporarily instead of Xaero's mods while waiting for 1.17 support.
  #voxelmap:
  #  # https://www.curseforge.com/minecraft/mc-mods/voxelmap
  #  id: { curseforge: 225179 }
---
# Dockerfile is generated from Dockerfile.liquid

# Use the same image as itzg/minecraft-server.
FROM adoptopenjdk:16-jre AS minecraft-base
RUN apt-get update
RUN \
  DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade && \
  apt-get clean
RUN \
  addgroup --gid 1000 minecraft && \
  adduser --system --home /minecraft --shell /bin/false --uid 1000 --ingroup minecraft minecraft && \
  mkdir -p /minecraft/server /minecraft/mods && \
  chown -R minecraft:minecraft /minecraft

FROM minecraft-base AS minecraft-download
RUN \
  DEBIAN_FRONTEND=noninteractive apt-get install -y wget && \
  apt-get clean
COPY download-mod /

FROM minecraft-download AS minecraft-server
USER minecraft
WORKDIR /minecraft/server
RUN wget -nc -O ../fabric-installer.jar {{ fabricInstallerURL | shell_escape }}
RUN \
  java -jar ../fabric-installer.jar server \
  -mcversion {{ minecraftVersion | shell_escape }} \
  -loaderversion {{ fabricLoaderVersion | shell_escape }} \
  -downloadMinecraft

{% for mod in mods -%}
FROM minecraft-download AS minecraft-mod-{{ mod.id | shell_escape }}
USER minecraft
WORKDIR /minecraft/mods
RUN /download-mod {{ mod.filename | shell_escape }}{% for url in mod.urls %} {{ url | shell_escape }}{% endfor %}

{% endfor -%}
FROM minecraft-base
VOLUME /data
RUN \
  mkdir -p /data && \
  chown -R minecraft:minecraft /data
USER minecraft
WORKDIR /data

COPY --from=minecraft-server /minecraft/server/*.jar /minecraft/server/
COPY --from=itzg/minecraft-server /usr/local/bin/mc-server-runner /usr/local/bin/
COPY --from=itzg/minecraft-server /usr/local/bin/mc-monitor /usr/local/bin/
COPY --from=itzg/minecraft-server /usr/local/bin/rcon-cli /usr/local/bin/
{% for mod in mods -%}
COPY --from=minecraft-mod-{{ mod.id | shell_escape }} /minecraft/mods/{{ mod.filename | shell_escape }} /minecraft/mods/
{% endfor -%}
COPY rcon /
COPY log4j2.xml /minecraft/
COPY start health-check /
EXPOSE 25565
ENTRYPOINT ["/start"]
HEALTHCHECK --start-period=1m CMD ["/health-check"]
